### PR TITLE
Width and Spelling Fixes

### PR DESCRIPTION
**Pull request by mtabor66**
fixed card box overflow and spelled Kanye correctly

there should no longer be a sideways scrollbar on careers.html and personal.html, and index.html when clicking from another page

### CODE REVIEW

**Comment by Cluttered04** [comment]
🐕

**Comment by iamnickmitchell** [comment]
🔨

**Comment by Havey3** [comment]
👯‍♂️ 👯

**Comment by iamnickmitchell** [comment]
🕺

**Pull request merged**
